[tool.poetry]
name = "graphml2mermaid"
version = "0.1.0"
description = ""
authors = ["Daniel Bradburn"]

[tool.poetry.dependencies]
python = "^3.8"
networkx = "^2.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
